/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formpembeli;

import controller.*;
import entitas.*;
import formadmin.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Ilham Bayu Sabdani
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form MANAGEFILM
     */
 
    private modelpembeli beli;
    int dragx,dragy;
    
    public register() throws SQLException {
        initComponents();
        this.beli = new modelpembeli();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        noktp = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        no_telp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        namauser = new javax.swing.JTextField();
        idreg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        create.setBackground(new java.awt.Color(0, 204, 204));
        create.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("CREATE ACCOUNT");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        getContentPane().add(create);
        create.setBounds(90, 440, 230, 23);

        jLabel12.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 360, 80, 20);

        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setOpaque(false);
        getContentPane().add(password);
        password.setBounds(40, 380, 320, 30);

        jLabel10.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NO TELPON");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 300, 80, 20);

        jLabel9.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ALAMAT");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 240, 110, 20);

        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.setOpaque(false);
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat);
        alamat.setBounds(40, 260, 320, 30);

        jLabel8.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NO KTP");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 180, 110, 20);

        noktp.setForeground(new java.awt.Color(255, 255, 255));
        noktp.setOpaque(false);
        noktp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noktpActionPerformed(evt);
            }
        });
        getContentPane().add(noktp);
        noktp.setBounds(40, 200, 320, 30);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/EXIT.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 0, 50, 50);

        jLabel6.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 300, 80, 20);

        no_telp.setForeground(new java.awt.Color(255, 255, 255));
        no_telp.setOpaque(false);
        getContentPane().add(no_telp);
        no_telp.setBounds(40, 320, 320, 30);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA USER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 120, 110, 20);

        namauser.setForeground(new java.awt.Color(255, 255, 255));
        namauser.setOpaque(false);
        namauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namauserActionPerformed(evt);
            }
        });
        getContentPane().add(namauser);
        namauser.setBounds(40, 140, 320, 30);

        idreg.setForeground(new java.awt.Color(255, 255, 255));
        idreg.setOpaque(false);
        getContentPane().add(idreg);
        idreg.setBounds(40, 80, 320, 30);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID RERGISTER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 80, 20);

        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 420, 570);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FORM REG.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 650);

        setSize(new java.awt.Dimension(417, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragx,y - dragy);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        dragx = evt.getX();
        dragy = evt.getY();
    }//GEN-LAST:event_jLabel7MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            new loginpem().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void namauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namauserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namauserActionPerformed

    private void noktpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noktpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noktpActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

        private void kosong()
    {
        idreg.setText("");
        noktp.setText("");
        alamat.setText("");
        namauser.setText("");
        no_telp.setText("");
        password.setText("");
    }

    
    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        Pelanggan reg = new Pelanggan();
        Register pem = new Register();
        try {
            pem.setIdregister(Integer.parseInt(idreg.getText()));
            pem.setNama(namauser.getText());
            pem.setAlamat(alamat.getText());
            pem.setTelp(Integer.parseInt(no_telp.getText()));
            
            reg.setKode_Reg(Integer.parseInt(idreg.getText()));
            reg.setPassword(password.getText());
            
            reg.setRegister(pem);
            pem.setpel(reg);
            
            this.beli.insertuser(pem, namauser.getText());
            kosong();
            JOptionPane.showMessageDialog(null,"BERHASIL DI REGISTRASI");
        } catch (SQLException err) {
            System.out.println(err);
        }

        
    }//GEN-LAST:event_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new register().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton create;
    private javax.swing.JTextField idreg;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField namauser;
    private javax.swing.JTextField no_telp;
    private javax.swing.JTextField noktp;
    private javax.swing.JTextField password;
    // End of variables declaration//GEN-END:variables
}
