/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formpembeli;

import controller.*;
import entitas.*;
import formadmin.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import tiket.bioskop.COVER;
 
/**
 *
 * @author Ilham Bayu Sabdani
 */
public class transaksi extends javax.swing.JFrame {

    /**
     * Creates new form MANAGEFILM
     */

    private modelpembeli beli;
    private modelcinema cinema;
    private ArrayList<Set_07056> arrHV;
    private Integer hargatotal;

    
    Integer kodereg;
    String ddk;
    int dragx,dragy;
    public transaksi()
    {
        
    }
    
    public transaksi(String i, Integer x) throws SQLException {
        initComponents();
        this.cinema = new modelcinema();
        this.beli = new modelpembeli();
        this.arrHV = new ArrayList<>();
        this.hargatotal=0;
        this.showTableJadwal();
        this.showComboBoxJadwal();
        user.setText(i);
        user1.setText(x.toString());
//        tabel2.setModel(data07065.datajadwal.viewTabel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();
        print = new javax.swing.JButton();
        item = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bnyk = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        a1 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        a4 = new javax.swing.JButton();
        a5 = new javax.swing.JButton();
        a6 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        d1 = new javax.swing.JButton();
        d2 = new javax.swing.JButton();
        d3 = new javax.swing.JButton();
        d4 = new javax.swing.JButton();
        d5 = new javax.swing.JButton();
        d6 = new javax.swing.JButton();
        kodetiket = new javax.swing.JTextField();
        user1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 450, 400, 110);

        print.setBackground(new java.awt.Color(0, 204, 204));
        print.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("PRINT STRUCT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(90, 590, 230, 23);

        getContentPane().add(item);
        item.setBounds(40, 190, 320, 30);

        jLabel10.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pilih kode ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 170, 80, 20);

        jLabel5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("kode reg");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 60, 50, 20);

        bnyk.setForeground(new java.awt.Color(255, 255, 255));
        bnyk.setOpaque(false);
        bnyk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnykActionPerformed(evt);
            }
        });
        getContentPane().add(bnyk);
        bnyk.setBounds(40, 250, 320, 30);

        jLabel11.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Banyak tiket");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 230, 110, 20);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/EXIT.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 0, 50, 50);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kode tiket");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 110, 110, 20);

        a1.setText("A1");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(20, 290, 50, 25);

        a2.setText("A2");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        getContentPane().add(a2);
        a2.setBounds(80, 290, 50, 25);

        a3.setText("A3");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        getContentPane().add(a3);
        a3.setBounds(140, 290, 50, 25);

        a4.setText("A4");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        getContentPane().add(a4);
        a4.setBounds(200, 290, 50, 25);

        a5.setText("A5");
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        getContentPane().add(a5);
        a5.setBounds(280, 290, 50, 25);

        a6.setText("A6");
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        getContentPane().add(a6);
        a6.setBounds(340, 290, 50, 25);

        b1.setText("B1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(20, 330, 50, 25);

        b2.setText("B2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(80, 330, 50, 25);

        b3.setText("B3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(140, 330, 50, 25);

        b4.setText("B4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(200, 330, 50, 25);

        b5.setText("B5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(280, 330, 50, 25);

        b6.setText("B6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(340, 330, 50, 25);

        c1.setText("C1");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(20, 370, 50, 25);

        c2.setText("C2");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(80, 370, 50, 25);

        c3.setText("C3");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3);
        c3.setBounds(140, 370, 50, 25);

        c4.setText("C4");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        getContentPane().add(c4);
        c4.setBounds(200, 370, 50, 25);

        c5.setText("C5");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        getContentPane().add(c5);
        c5.setBounds(280, 370, 50, 25);

        c6.setText("C6");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        getContentPane().add(c6);
        c6.setBounds(340, 370, 50, 25);

        d1.setText("D1");
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        getContentPane().add(d1);
        d1.setBounds(20, 410, 50, 25);

        d2.setText("D2");
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        getContentPane().add(d2);
        d2.setBounds(80, 410, 50, 25);

        d3.setText("D3");
        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });
        getContentPane().add(d3);
        d3.setBounds(140, 410, 50, 25);

        d4.setText("D4");
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });
        getContentPane().add(d4);
        d4.setBounds(200, 410, 50, 25);

        d5.setText("D5");
        d5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d5ActionPerformed(evt);
            }
        });
        getContentPane().add(d5);
        d5.setBounds(280, 410, 50, 25);

        d6.setText("D6");
        d6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d6ActionPerformed(evt);
            }
        });
        getContentPane().add(d6);
        d6.setBounds(340, 410, 50, 25);

        kodetiket.setForeground(new java.awt.Color(255, 255, 255));
        kodetiket.setOpaque(false);
        kodetiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodetiketActionPerformed(evt);
            }
        });
        getContentPane().add(kodetiket);
        kodetiket.setBounds(40, 130, 320, 30);

        user1.setEditable(false);
        user1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        user1.setForeground(new java.awt.Color(255, 255, 255));
        user1.setOpaque(false);
        user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1ActionPerformed(evt);
            }
        });
        getContentPane().add(user1);
        user1.setBounds(260, 60, 100, 20);

        user.setEditable(false);
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setOpaque(false);
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(260, 20, 100, 30);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("user");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 20, 30, 30);

        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 420, 650);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRANSAKSI");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 170, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/luke-chesser-B_oL3jEt5L4-unsplash_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 650);

        setSize(new java.awt.Dimension(419, 651));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragx,y - dragy);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        dragx = evt.getX();
        dragy = evt.getY();
    }//GEN-LAST:event_jLabel7MousePressed

    private void showuser(String x) throws SQLException
    {
        
    }
    
    private void showTableJadwal() throws SQLException {
        DefaultTableModel dtmJadwal = new DefaultTableModel(new String[]{
            "KODE JADWAL", "NAMA FILM", "TANGGAL TAYANG", "WAKTU TAYANG", "RUANG"
        }, 0);
        dtmJadwal.setRowCount(0);

        for (Jadwal jd : this.cinema.getDataJadwal()) {
            dtmJadwal.addRow(new String[]{
                jd.getKode_Jadwal().toString(),
                jd.getFilm().getNama_Film(),
                jd.getTgl_Tayang().toString(), 
                jd.getWktu_Tayang(),
                jd.getRuang()
            });
        }
        this.tabel2.setModel(dtmJadwal);
    }

    private void showComboBoxJadwal() throws SQLException {
        DefaultComboBoxModel dcbmJadwal = new DefaultComboBoxModel();

        for (Jadwal jd : this.cinema.getDataJadwal()) {
            dcbmJadwal.addElement(jd.getKode_Jadwal().toString() + ") " + jd.getFilm().getNama_Film());
        }
        this.item.setModel(dcbmJadwal);
        
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         COVER a = new COVER();
         a.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void kodetiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodetiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodetiketActionPerformed

    private void bnykActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnykActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnykActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        Tiket trans = new Tiket();
        try {
            trans.setreg(beli.getDataReg().get(Integer.parseInt(user1.getText())-1));
            trans.setKode_Tiket(Integer.parseInt(kodetiket.getText()));
            trans.setBanyak(Integer.parseInt(bnyk.getText()));
            trans.setDuduk(ddk);
            trans.setarrHave(arrHV);
            
            Set_07056 sett = new Set_07056();
            sett.setjdwl(this.cinema.getDataJadwal().get(item.getSelectedIndex()));
            this.hargatotal += (this.cinema.getDataJadwal().get(item.getSelectedIndex()).getFilm().getHarga()* Integer.parseInt(bnyk.getText()));
            trans.setTotal(this.hargatotal);
            this.beli.inserttrans(trans);
            new struck(Integer.parseInt(user1.getText())-1).setVisible(true);
            setVisible(false);
        } catch (SQLException err) {
            System.out.println(err);
        }
        
    }//GEN-LAST:event_printActionPerformed

        
    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user1ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        a1.setBackground(new Color(204,0,0));
        ddk = a1.getText();
    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        a2.setBackground(new Color(204,0,0));
        ddk = a2.getText();
    }//GEN-LAST:event_a2ActionPerformed

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        a3.setBackground(new Color(204,0,0));
        ddk = a3.getText();
    }//GEN-LAST:event_a3ActionPerformed

    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        a4.setBackground(new Color(204,0,0));
        ddk = a4.getText();
    }//GEN-LAST:event_a4ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        a5.setBackground(new Color(204,0,0));
        ddk = a5.getText();
    }//GEN-LAST:event_a5ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        a6.setBackground(new Color(204,0,0));
        ddk = a6.getText();
    }//GEN-LAST:event_a6ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        b1.setBackground(new Color(204,0,0));
        ddk = b1.getText();
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        b2.setBackground(new Color(204,0,0));
        ddk = b2.getText();
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        b3.setBackground(new Color(204,0,0));
        ddk = b3.getText();
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        b4.setBackground(new Color(204,0,0));
        ddk = b4.getText();
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        b5.setBackground(new Color(204,0,0));
        ddk = b5.getText();
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        b6.setBackground(new Color(204,0,0));
        ddk = b6.getText();
    }//GEN-LAST:event_b6ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        c1.setBackground(new Color(204,0,0));
        ddk = c1.getText();
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        c2.setBackground(new Color(204,0,0));
        ddk = c2.getText();
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        c3.setBackground(new Color(204,0,0));
        ddk = c3.getText();
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        c4.setBackground(new Color(204,0,0));
        ddk = c4.getText();
    }//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        c5.setBackground(new Color(204,0,0));
        ddk = c5.getText();
    }//GEN-LAST:event_c5ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        c6.setBackground(new Color(204,0,0));
        ddk = c6.getText();
    }//GEN-LAST:event_c6ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        d1.setBackground(new Color(204,0,0));
        ddk = d1.getText();
    }//GEN-LAST:event_d1ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        d2.setBackground(new Color(204,0,0));
        ddk = d2.getText();
    }//GEN-LAST:event_d2ActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        d3.setBackground(new Color(204,0,0));
        ddk = d3.getText();
    }//GEN-LAST:event_d3ActionPerformed

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ActionPerformed
        d4.setBackground(new Color(204,0,0));
        ddk = d4.getText();
    }//GEN-LAST:event_d4ActionPerformed

    private void d5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d5ActionPerformed
        d5.setBackground(new Color(204,0,0));
        ddk = d5.getText();
    }//GEN-LAST:event_d5ActionPerformed

    private void d6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d6ActionPerformed
        d6.setBackground(new Color(204,0,0));
        ddk = d6.getText();
    }//GEN-LAST:event_d6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton a4;
    private javax.swing.JButton a5;
    private javax.swing.JButton a6;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JTextField bnyk;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton d1;
    private javax.swing.JButton d2;
    private javax.swing.JButton d3;
    private javax.swing.JButton d4;
    private javax.swing.JButton d5;
    private javax.swing.JButton d6;
    private javax.swing.JComboBox item;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodetiket;
    private javax.swing.JButton print;
    private javax.swing.JTable tabel2;
    public static final javax.swing.JTextField user = new javax.swing.JTextField();
    private javax.swing.JTextField user1;
    // End of variables declaration//GEN-END:variables
}
